apiVersion: batch/v1
kind: Job
metadata:
  generateName: kubescape-scan
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: kubescape
        image: quay.io/kubescape/kubescape-cli:v3.0.15
        command: ["kubescape"]
        args: ["scan", "--scan-images", "--compliance-threshold", "75", "--exclude-namespaces", "akuity,default,kube-node-lease,kube-public,kube-system"]
      restartPolicy: Never
